version: '2'
services:
    node:
        ports:
            - 3000:3000
        image: node:11.10-alpine
        container_name: udemy_nodecourse
        working_dir: /home/node/app
        environment:
            - NODE_ENV=dev
        volumes:
            - ./:/home/node/app
        expose: 
            - "3000"
        command: "npm start"
    db:
        ports:
            - 3306:3306
        image: mysql:8
        container_name: udemy_mysql_nodecourse
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
